server:
  port: 8011
  error:
    include-message: always
    include-binding-errors: always

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: property-management-service
          uri: lb://PROPERTY-MANAGEMENT-SERVICE
          predicates:
            - Path=/api/v1/pms/**

        - id: showcase-service
          uri: lb://SHOWCASE-SERVICE
          predicates:
            - Path=/api/v1/showcase/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
