server:
  port: 8011
  error:
    include-message: always
    include-binding-errors: always

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
              allowedOrigins: "*"
              allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              allowedHeaders:
              - "*"
      routes:
        - id: auth-service
          uri: lb://AUTHENTIFICATION
          predicates:
            - Path=/api/v1/auth/**

        - id: property-management-service
          uri: lb://PROPERTY-MANAGEMENT-SERVICE
          predicates:
            - Path=/api/v1/pms/**
          filters:
            - AuthenticationFilter

        - id: showcase-service
          uri: lb://SHOWCASE-SERVICE
          predicates:
            - Path=/api/v1/showcase/**
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
logging:
  level:
    org:
      springframework:
        cloud:
          gateway: trace
          openfeign: trace
          webClient: trace


